"""`ir help` — one-screen explainer.

Plain stdout (no rich dependency) so it stays fast on cold-start.
"""

from __future__ import annotations

from . import models


def run(args=None) -> int:
    lines: list[str] = []
    lines.append("")
    lines.append("ir — Claude Code, routed through inferroute")
    lines.append("")
    lines.append("Getting started")
    lines.append("  ir setup                 First time? Log in + optionally enable recording, in one step")
    lines.append("")
    lines.append("Daily use")
    lines.append("  ir                       Open the model picker, then launch (same as `ir choose`)")
    lines.append("  ir --model NAME          Pin a specific model (any claude flag also passes through)")
    lines.append("")
    lines.append("    NAME can be a short alias or the canonical id. Known short aliases:")
    for a in models.all_aliases():
        lines.append(f"      {a.short:<10} → {a.label}")
    lines.append("    Anything else (e.g. claude-opus-4-8, claude-sonnet-4-6) passes through verbatim.")
    lines.append("")
    lines.append("  ir choose                Same as bare `ir` — interactive picker, then launch")
    lines.append("  ir anthropic             Escape hatch — plain claude, no inferroute env touched")
    lines.append("")
    lines.append("Cowork — a desktop app for everyday work, powered by goose")
    lines.append("  ir cowork                Wire goose to inferroute and launch it (the desktop app if")
    lines.append("                           installed, else the CLI). Point-and-click; no terminal needed.")
    lines.append("  ir cowork --cli          Force the goose CLI instead of the desktop")
    lines.append("  ir cowork --configure-only")
    lines.append("                           Wire goose to inferroute without launching")
    lines.append("")
    lines.append("Deferred / economy lane")
    lines.append("  ir gate        Poll the economy gate. Exit 0 = cheap window (run a cycle),")
    lines.append("                 1 = skip. Use in a loop: `if ir gate; then run; else sleep 30; fi`")
    lines.append("                 `ir gate --print-env` emits the economy ANTHROPIC_BASE_URL exports.")
    lines.append("  ir integrate-deferral-gate")
    lines.append("                 An agent wires this repo's autonomous loop to the")
    lines.append("                 economy lane (runs cheap in off-peak windows).")
    lines.append("")
    lines.append("Account")
    lines.append("  ir login       Save your inferroute API key (one-time)")
    lines.append("  ir logout      Remove the saved inferroute API key")
    lines.append("  ir status      Personal usage + recent requests (TUI)")
    lines.append("")
    lines.append("Local recording (optional, fully private)")
    lines.append("  ir add recording")
    lines.append("                 Run a small daemon on localhost:5005 that records — on THIS")
    lines.append("                 machine only — which model you pick per task and how it went.")
    lines.append("                 Never uploaded; we never see it. ~15 MB of deps.")
    lines.append("  ir data show   See what's recorded (counts, models, size)")
    lines.append("  ir data wipe   Delete it all   ·   ir data export <dir>  copy metadata layer")
    lines.append("  ir remove recording")
    lines.append("                 Reverse the above. `--purge` also deletes the recorded data.")
    lines.append("")
    lines.append("How it works")
    lines.append("  Every command spawns `claude` as a subprocess and adds")
    lines.append("  --dangerously-skip-permissions so the agent runs without prompts.")
    lines.append("")
    lines.append("  The routed commands (`ir`, `ir --model …`) set ANTHROPIC_BASE_URL")
    lines.append("  to https://api.inferroute.ai and use your saved key — only for")
    lines.append("  that spawned process. Your shell stays untouched.")
    lines.append("")
    lines.append("  `ir anthropic` does NOT touch the env — it's pure pass-through.")
    lines.append("  Whatever your `claude` does normally, that's what happens.")
    lines.append("")
    lines.append("Where things live")
    lines.append("  ~/.config/inferroute/credentials   your API key (mode 600)")
    lines.append("")
    lines.append("Sign up: https://inferroute.ai")
    lines.append("Source:  https://github.com/InferRoute/inferroute")
    lines.append("")
    print("\n".join(lines))
    return 0
